spring:
  liquibase:
    contexts: test-data
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  docker:
    compose:
      file: compose.yaml
      lifecycle-management: start_and_stop
      stop:
        command: down
      profiles:
        active: database